version: '3.4'

services:
  catalogueDb:
    image: mongo
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalogue/Catalog.API/Dockerfile
volumes:
  mongo_data: